WHOIS_LOOKUP_COUNT = 5
WHOIS_LOOKUP_WAIT_MIN = 1
WHOIS_LOOKUP_WAIT_MAX = 3

IGNORE_LIST = ['knight22.com', '10.0.0.31', '10.0.0.2', 'local']

SUMMARY_GEN = True
GRAPH_GEN = False
LOOKUP_TLD_INFO = True